// Expense model - defines the structure of a single expense entry
// each expense gets saved as a row in the SQLite database

class Expense {
  final int? id;          // auto-generated by SQLite, null before saving
  final String title;     // what the expense was for
  final double amount;    // how much was spent
  final String category;  // food, transport, housing, etc.
  final String date;      // format: yyyy-MM-dd

  Expense({
    this.id,
    required this.title,
    required this.amount,
    required this.category,
    required this.date,
  });

  // convert object to Map so SQLite can store it
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'title': title,
      'amount': amount,
      'category': category,
      'date': date,
    };
  }

  // build an Expense object from a SQLite row
  factory Expense.fromMap(Map<String, dynamic> map) {
    return Expense(
      id: map['id'],
      title: map['title'],
      amount: map['amount'],
      category: map['category'],
      date: map['date'],
    );
  }
}